import React from 'react';
import { Link } from 'react-router-dom';
import Button from '../components/ui/Button';
import Card from '../components/ui/Card';
import { useAuth } from '../hooks/useAuth';

const HomePage: React.FC = () => {
    const { isAuthenticated } = useAuth();
  return (
    <div className="text-center py-16">
      <div 
        className="absolute top-0 left-0 w-full h-full bg-grid-cyan-500/[0.2] [mask-image:linear-gradient(to_bottom,white_5%,transparent_50%)] z-0"
      ></div>
      <div className="relative z-10">
        <h1 className="text-5xl md:text-7xl font-extrabold mb-4 bg-clip-text text-transparent bg-gradient-to-r from-yellow-400 to-yellow-200">
          Ace Your Next Interview
        </h1>
        <p className="text-lg md:text-xl text-gray-300 max-w-3xl mx-auto mb-8">
          Harness the power of AI to practice, get instant feedback, and track your progress. Land your dream job with confidence.
        </p>
        <div className="flex justify-center items-center space-x-4 mb-24">
            <Link to="/interviews">
                <Button variant="primary" className="text-lg">
                    Start Practicing Now
                </Button>
            </Link>
            <Link to="/about">
                <Button variant="ghost" className="text-lg">
                    Learn More <i className="fas fa-arrow-right ml-2"></i>
                </Button>
            </Link>
        </div>
        
        <div className="max-w-5xl mx-auto">
          <h2 className="text-3xl font-bold mb-10">Key Features</h2>
          <div className="grid md:grid-cols-3 gap-8 text-left">
            <Card>
              <div className="p-4">
                <i className="fas fa-question-circle text-yellow-400 text-3xl mb-4"></i>
                <h3 className="text-xl font-bold mb-2">Dynamic Questions</h3>
                <p className="text-gray-400">Receive a unique set of interview questions tailored to your chosen field and specialization, generated by our advanced AI.</p>
              </div>
            </Card>
            <Card>
              <div className="p-4">
                <i className="fas fa-chart-line text-yellow-400 text-3xl mb-4"></i>
                <h3 className="text-xl font-bold mb-2">Instant AI Feedback</h3>
                <p className="text-gray-400">Get a detailed analysis of your answers, with scores and feedback on fluency, tone, grammar, and content quality.</p>
              </div>
            </Card>
            <Card>
              <div className="p-4">
                <i className="fas fa-history text-yellow-400 text-3xl mb-4"></i>
                <h3 className="text-xl font-bold mb-2">Track Your Progress</h3>
                <p className="text-gray-400">Save your sessions and visualize your improvement over time with our progress tracker, helping you identify strengths and weaknesses.</p>
              </div>
            </Card>
          </div>
        </div>

        {!isAuthenticated && (
            <div className="mt-24 p-6 bg-gray-800/50 rounded-lg max-w-2xl mx-auto backdrop-blur-sm">
                <h2 className="text-2xl font-bold text-yellow-400">Ready to level up?</h2>
                <p className="mt-2 text-gray-400">Login to save your sessions and track your improvement over time.</p>
            </div>
        )}
      </div>
    </div>
  );
};

export default HomePage;